### ISSUE TITLE
demo/bug: kuramoto_demo

### ISSUE THREAD

**Issue by sameerashahh** [DynaDojo/dynadojo#53]
**Describe the bug**
Incorrect argument ('legend_labels') in plot()

**To Reproduce**
1. Go to demos/systems/kuramoto_demo.ipynb
2. Run the demo cell by cell.
4. Error occurs when last cell is run.

**Expected behavior**
Plots should generate according to the inputs.

**Comment by lmclane04** [comment]
Replace "legend_labels" with "labels".
