### ISSUE TITLE
demo/bug: hot_dino

### ISSUE THREAD

**Issue by sameerashahh** [DynaDojo/dynadojo#56]
**Describe the bug**
File not found for dino.png

**To Reproduce**
1. Go to demos/systems/hot_dino.ipynb
2. Run the demo cell by cell.
3. Error occurs in the 3rd cell.

**Expected behavior**
A plot should generate.

**Comment by lmclane04** [comment]
Replace "../graphics/dino.png" with "../../graphics/dino.png" anywhere where it appears in the code. 
This makes it so that we access graphics/dino.png from the grandparent branch of our current branch (main) instead of the parent branch of our current branch (demos).
