### ISSUE TITLE
demo/feat: missing system/lds demo

### ISSUE THREAD

**Issue by sameerashahh** [DynaDojo/dynadojo#66]
**Is your feature request related to a problem? Please describe.**
There is no separate demo for the Linear Dynamical system.

**Describe the solution you'd like**
A demo for the Linear Dynamical system should be implemented in the project.

**Comment by carynbear** [comment]
Reference https://github.com/DynaDojo/dynadojo/blob/main/demos/fts_dmd_lds_demo.ipynb to make a system-only demo for LDS.
