### ISSUE TITLE
demo/feat: missing system/lorenz demo

### ISSUE THREAD

**Issue by sameerashahh** [DynaDojo/dynadojo#67]
**Is your feature request related to a problem? Please describe.**
There is no separate demo for the Lorenz system.

**Describe the solution you'd like**
A demo for the Lorenz system should be implemented in the project.

**Comment by carynbear** [comment]
See https://github.com/DynaDojo/dynadojo/blob/main/demos/algorithms/sindy_lorenz_demo1.ipynb.
