### ISSUE TITLE
demo/bug: dnn_vs_gru_demo

### ISSUE THREAD

**Issue by sameerashahh** [DynaDojo/dynadojo#82]
**Describe the bug**
ModuleNotFoundError: No module named 'dynadojo.baselines.gru_rnn'

**To Reproduce**
1. Go to demos/algorithms/dnn_vs_gru.ipynb
2. Run cell by cell
3. Error occurs in 2nd cell.

**Expected behavior**
Imports should happen correctly.

**Comment by carynbear** [comment]
Assigned to Vincent

**Comment by VictorHuynh** [comment]
Unable to import because the gru_rnn algorithm does not yet exist within the main branch's baselines folder.
But it looks like there is a can-gru-rnn branch in the works, which when merged, should solve this import issue!
https://github.com/DynaDojo/dynadojo/tree/can-gru-rnn
